In [1]:
import pandas as pd

import matplotlib.pyplot as plt

In [2]:
x = pd.read_csv('/Users/Hookay/Desktop/Road signs/x_train_gr_smpl.csv')

In [3]:
y=pd.read_csv('/Users/Hookay/Desktop/Road signs/y_train_smpl.csv')

In [4]:

# def split_train_test(data, test_ratio):
#      shuffled_indices = np.random.permutation(len(data))
#      test_set_size = int(len(data) * test_ratio)
#      test_indices = shuffled_indices[:test_set_size]
#      train_indices = shuffled_indices[test_set_size:]
#      return data.iloc[train_indices], data.iloc[test_indices]

from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.2)

In [5]:
from sklearn.naive_bayes import GaussianNB

In [6]:
gnb = GaussianNB()

In [7]:
from sklearn.naive_bayes import MultinomialNB

In [9]:
import numpy as np
#  it asked me to make a row from the column vector
y_train = np.ravel(y_train)

model = MultinomialNB().fit(x_train, y_train)

In [11]:
predicted = model.predict(x_test)

In [12]:
from sklearn.metrics import confusion_matrix
# this is for the multinomial
print(confusion_matrix(y_test, predicted))

[[ 11   6  11   7   4   0   0   0   0   1]
 [ 99  70  85  64  95   2   8   1   4  18]
 [ 30  31 153  71 183   7   4   0   2  10]
 [ 19  24  35 106  78   0   1   0   1   0]
 [ 16  22  23  64 231   1   3   0   1   7]
 [  0   0   2   0   0  30   0   1   6   2]
 [  0   2   0   6   2  24  10   5   8   1]
 [  0   0   0   7   0  23   4  18   2   3]
 [  1   0   2   5   0  45  16  14  30   0]
 [  0   3   4   6   3  19   1   6   1  17]]


In [17]:
gnb.fit(x_train, y_train)

GaussianNB()

In [18]:
y_pred = gnb.predict(x_test)

In [19]:
# this is for the gaussian
from sklearn import metrics
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))

Accuracy: 0.22961816305469557


In [20]:
# this is for the gaussian
print(confusion_matrix(y_test, y_pred))

[[ 28   3   4   4   1   0   0   0   0   0]
 [100  90  52  21  29   7  57  78   3   9]
 [ 26  87  80  43  64  16  77  82   0  16]
 [  6   8   5  63   8   5 156   9   1   3]
 [  7  42  30  20  55   6 172  33   0   3]
 [  1   1   2   0   0  11  11  13   2   0]
 [  0   1   0   2   0   1  34  11   0   9]
 [  1   0   0   3   0   0  11  37   1   4]
 [  4   7   7   0   0   6  26  30  31   2]
 [  0   2   0   0   0   1   4  35   2  16]]


In [21]:
# this is for the multinomial
from sklearn import metrics
print("Accuracy:",metrics.accuracy_score(y_test, predicted ))

Accuracy: 0.34881320949432404


In [22]:
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score

In [24]:
y_train.shape,y_test.shape


((7752,), (1938, 1))